# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DepositCalenderApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DepositCalenderApp
pod 'PopupDialog', '~> 0.5'
pod 'KMPlaceholderTextView', '~> 1.3.0'

  target 'DepositCalenderAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DepositCalenderAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
